import { useEffect, useState } from "react";
import axios from "axios";
import { Sparkles, Moon, Sun, ArrowRight, Upload, MessageCircle, ShieldCheck, Stars, LogOut, UserRound, ChevronRight, Check, Menu, X, HelpCircle, FileText, Heart, MapPin, Lock } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const api = axios.create({ baseURL: API });
const img = { cosmos: "https://images.unsplash.com/photo-1528722828814-77b9b83aafb2?auto=format&fit=crop&w=1800&q=85", palm: "https://images.pexels.com/photos/6642895/pexels-photo-6642895.jpeg?auto=compress&cs=tinysrgb&w=900", chart: "https://images.unsplash.com/photo-1729335511904-9b8690184935?auto=format&fit=crop&w=900&q=85" };
const navItems = ["Overview", "Palm Reading", "Kundli", "Compatibility", "Pricing"];

function Auth({ onAuth, onClose }) { const [mode,setMode]=useState("login"); const [form,setForm]=useState({email:"",password:""}); const [error,setError]=useState("");
  const submit=async(e)=>{e.preventDefault();setError("");try{const r=await api.post(`/auth/${mode}`,form);localStorage.setItem("astro_token",r.data.token);onAuth(r.data.user)}catch(err){setError(err.response?.data?.detail||"Please try again")}};
  return <div className="modal-backdrop"><div className="auth-modal"><button className="icon-btn close" data-testid="auth-close-button" onClick={onClose}><X/></button><span className="eyebrow">YOUR PRIVATE COSMOS</span><h2>{mode==="login"?"Welcome back":"Begin your journey"}</h2><p className="muted">Save your chart, readings, and conversations in one place.</p><form onSubmit={submit} data-testid="auth-form"><label>Email<input data-testid="auth-email-input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input data-testid="auth-password-input" type="password" minLength="6" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="error" data-testid="auth-error">{error}</div>}<button className="gold-btn full" data-testid="auth-submit-button">{mode==="login"?"Sign in":"Create account"}<ArrowRight size={16}/></button></form><button className="text-btn" data-testid="auth-mode-toggle" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"New to AstroAI? Create an account":"Already have an account? Sign in"}</button></div></div> }

function App(){ const [user,setUser]=useState(null),[auth,setAuth]=useState(false),[view,setView]=useState("Overview"),[mobile,setMobile]=useState(false),[kundli,setKundli]=useState(null),[palm,setPalm]=useState(null); const [loading,setLoading]=useState(false); const [toast,setToast]=useState(null); const [pkg,setPkg]=useState(null);
  const notify=(message,tone="error")=>{setToast({message,tone});setTimeout(()=>setToast(null),5200)};
  const hydrateDashboard=()=>api.get("/dashboard").then(r=>{if(r.data.kundli)setKundli(r.data.kundli)}).catch(()=>{});
  useEffect(()=>{const token=localStorage.getItem("astro_token");if(token){api.defaults.headers.common.Authorization=`Bearer ${token}`;api.get("/auth/me").then(r=>{setUser(r.data);return hydrateDashboard()}).catch(()=>localStorage.removeItem("astro_token"))}},[]);
  const go=(v)=>{setView(v);setMobile(false)}; const signIn=(u)=>{api.defaults.headers.common.Authorization=`Bearer ${localStorage.getItem("astro_token")}`;setUser(u);hydrateDashboard();setAuth(false);go("Dashboard")}; const signOut=()=>{localStorage.removeItem("astro_token");delete api.defaults.headers.common.Authorization;setUser(null);setKundli(null);go("Overview")};
  const startPackage=(id)=>{setPkg(id);go("Checkout")};
  const proceedFromCheckout=()=>{if(pkg==="palm")go("Palm Reading");else if(pkg==="kundli")go("Kundli");else if(pkg==="bundle")go("Kundli")};
  const createKundli=async(data)=>{if(!user){setAuth(true);return}setLoading(true);try{const r=await api.post("/kundli",data);setKundli(r.data);go("Kundli result")}catch(e){notify(e.response?.data?.detail||"Could not create Kundli")}finally{setLoading(false)}};
  const sendPalm=async(data)=>{if(!user){setAuth(true);return}setLoading(true);try{const r=await api.post("/palm",data);setPalm(r.data);go("Palm result")}catch(e){notify(e.response?.data?.detail||"Could not read this image")}finally{setLoading(false)}};
  return <div className="app-shell"><header className="topbar"><button className="brand" data-testid="brand-home-button" onClick={()=>go("Overview")}><span className="brand-mark"><Stars size={20}/></span><span>ASTRO<span>AI</span></span></button><nav className={mobile?"nav open":"nav"}>{navItems.map(n=><button key={n} data-testid={`nav-${n.toLowerCase().replaceAll(" ","-")}-button`} className={view.startsWith(n)?"active":""} onClick={()=>go(n)}>{n}</button>)}</nav><div className="top-actions">{user?<><button className="avatar-btn" data-testid="dashboard-button" onClick={()=>go("Dashboard")}><UserRound size={17}/>{user.email.split("@")[0]}</button><button className="icon-btn" data-testid="logout-button" onClick={signOut}><LogOut size={17}/></button></>:<button className="outline-btn" data-testid="sign-in-button" onClick={()=>setAuth(true)}>Sign in</button>}<button className="menu-btn" data-testid="mobile-menu-button" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
    <main>{view==="Overview"&&<Home go={go} user={user} startPackage={startPackage}/>} {view==="Palm Reading"&&<PalmFlow onSubmit={sendPalm} loading={loading}/>} {view==="Palm result"&&<PalmResult data={palm} go={go}/>} {view==="Kundli"&&<KundliForm onSubmit={createKundli} loading={loading} notify={notify} isBundle={pkg==="bundle"} go={go}/>} {view==="Kundli result"&&<KundliResult data={kundli} go={go} isBundle={pkg==="bundle"}/>} {view==="Dashboard"&&<Dashboard user={user} kundli={kundli} go={go}/>} {view==="Compatibility"&&<Compatibility/>} {view==="Pricing"&&<Pricing startPackage={startPackage}/>} {view==="Checkout"&&<Checkout pkg={pkg} onProceed={proceedFromCheckout} go={go} notify={notify}/>}</main>{auth&&<Auth onAuth={signIn} onClose={()=>setAuth(false)}/>}{toast&&<div className={`toast toast-${toast.tone}`} data-testid="app-toast" role="alert"><span>{toast.message}</span><button onClick={()=>setToast(null)} className="icon-btn" data-testid="toast-dismiss"><X size={16}/></button></div>}<footer><div className="brand footer-brand"><span className="brand-mark"><Stars size={18}/></span><span>ASTRO<span>AI</span></span></div><span>Traditional wisdom, thoughtfully interpreted.</span><span>© 2025 AstroAI · Privacy · Terms</span></footer></div> }

function Home({go,user,startPackage}){return <><section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(9,13,25,.95),rgba(9,13,25,.55)),url(${img.cosmos})`}}><div className="hero-copy"><div className="eyebrow"><Sun size={14}/> ANCIENT WISDOM · INTELLIGENTLY REVEALED</div><h1>Discover what your <em>stars</em><br/> & palm reveal.</h1><p>Explore your Vedic Kundli and AI-powered palm reading in one personalized experience.</p><div className="hero-actions"><button className="gold-btn" data-testid="hero-read-palm-button" onClick={()=>startPackage("palm")}><Upload size={17}/> Read my palm — ₹99</button><button className="ghost-btn" data-testid="hero-create-kundli-button" onClick={()=>startPackage("kundli")}>Create my Kundli — ₹99 <ArrowRight size={17}/></button></div><div className="trust-row"><ShieldCheck size={16}/><span>Private by design</span><span className="dot"/><span>Responsible guidance</span></div></div><div className="hero-stat"><span className="eyebrow">A PERSONAL COSMIC MAP</span><strong>01</strong><span>Begin with your birth story<br/>or the lines in your hand.</span></div></section>
  <section className="intro section"><div><span className="eyebrow">THE ASTROAI METHOD</span><h2>A quieter way to<br/><em>look inward.</em></h2></div><p className="lead">AstroAI blends Vedic tradition with thoughtful artificial intelligence — turning complex patterns into reflective, personal guidance you can return to.</p></section>
  <section className="section how-it-works" data-testid="home-how-it-works"><span className="eyebrow">HOW IT WORKS</span><h2>Three small steps,<br/><em>one clearer picture.</em></h2><div className="steps-grid">{[{n:"01",t:"Share what you know",d:"Your birth details or a clear palm photograph — never more than you're comfortable with."},{n:"02",t:"Traditional calculation",d:"Swiss Ephemeris resolves your sidereal chart. Palm images are read with careful vision AI."},{n:"03",t:"Reflective reading",d:"Grounded interpretations you can return to, and a chart chat when you want to dig deeper."}].map(s=><div className="step-card" key={s.n}><strong>{s.n}</strong><h3>{s.t}</h3><p>{s.d}</p></div>)}</div></section>
  <section className="feature-grid section"><Feature image={img.palm} label="01 / PALMISTRY" title="The story in your hands." text="Upload a clear photo and receive a considered reading of your major lines, patterns, strengths, and challenges." button="Read my palm" onClick={()=>startPackage("palm")}/><Feature image={img.chart} label="02 / VEDIC ASTROLOGY" title="Your map through time." text="Build a personal Kundli with your exact birth details, then explore interpretations for the chapters that matter." button="Create my Kundli" onClick={()=>startPackage("kundli")} /></section>
  <section className="band"><div className="section band-inner"><div><span className="eyebrow">ASK YOUR KUNDLI</span><h2>Curiosity is<br/><em>a compass.</em></h2></div><div className="quote"><MessageCircle size={22}/><p>“What does my 10th house indicate?”</p><span>Ask grounded questions about your personal chart.</span><button className="text-link" data-testid="home-chat-button" onClick={()=>user?go("Dashboard"):go("Kundli")}>Explore your chart <ChevronRight size={16}/></button></div></div></section>
  <section className="section teaser-grid" data-testid="home-compat-samples"><article className="teaser"><Heart size={20}/><span className="eyebrow">COMPATIBILITY</span><h3>Two charts,<br/><em>one shared sky.</em></h3><p>Traditional Guna Milan and communication tendencies for the pair. Not a verdict on love.</p><button className="text-link" data-testid="home-compat-teaser" onClick={()=>go("Compatibility")}>See how it works <ArrowRight size={15}/></button></article><article className="teaser"><FileText size={20}/><span className="eyebrow">SAMPLE REPORTS</span><h3>Read a<br/><em>real reading.</em></h3><p>Excerpted from actual charts — career emphasis, current Dasha themes, and reflective palm notes.</p><ul className="sample-list"><li>“Career emphasis via a strong 10th house Sun in Vrishabha.”</li><li>“A deep heart line suggesting steady, considered attachment.”</li><li>“Current Venus Mahadasha: relational reflection, artistic pull.”</li></ul></article></section>
  <section className="section pricing home-pricing" data-testid="home-pricing"><span className="eyebrow">PRICING</span><h1 className="pricing-heading">Choose your<br/><em>constellation.</em></h1><PricingCards startPackage={startPackage}/><p className="micro-note" data-testid="pricing-savings-note">Palm Reading + Kundli separately: ₹198 · Bundle: ₹159 · You save ₹39. Payment gateway integration required to activate purchases; see Checkout for status.</p></section>
  <section className="section faq" data-testid="home-faq"><span className="eyebrow">FREQUENTLY ASKED</span><h2>Small doubts,<br/><em>clear answers.</em></h2><div className="faq-list">{[{q:"Is astrology scientifically proven?",a:"No. Vedic astrology and palmistry are traditional and spiritual practices — reflective, not predictive of guaranteed outcomes."},{q:"How are planetary positions calculated?",a:"Server-side using Swiss Ephemeris with the Lahiri sidereal system. AI only interprets values returned by the calculation engine."},{q:"What happens to my palm photo?",a:"Only used to generate this reading. You can remove your account and personal data from your dashboard."},{q:"Do you make predictions like wealth or marriage dates?",a:"No. Responses stay reflective — never absolute claims about wealth, marriage, health, or death."}].map(f=><details key={f.q} className="faq-item"><summary><HelpCircle size={15}/><span>{f.q}</span></summary><p>{f.a}</p></details>)}</div></section>
  <section className="disclaimer section" data-testid="home-disclaimer"><span className="eyebrow">A NOTE ON RESPONSIBILITY</span><p>Astrology and palmistry are traditional and spiritual practices, not scientifically validated methods of predicting the future. AstroAI offers reflective guidance — never medical advice, guarantees, or absolute predictions.</p></section></>}
function Feature({image,label,title,text,button,onClick}){return <article className="feature"><div className="feature-image"><img src={image} alt=""/><span>{label}</span></div><div className="feature-copy"><h3>{title}</h3><p>{text}</p><button className="text-link" data-testid={`${button.toLowerCase().replaceAll(" ","-")}-feature-button`} onClick={onClick}>{button}<ArrowRight size={16}/></button></div></article>}
function PalmFlow({onSubmit,loading}){const [image,setImage]=useState(null),[hand,setHand]=useState("right");const upload=e=>{const f=e.target.files[0];if(f){const r=new FileReader();r.onload=()=>setImage(r.result);r.readAsDataURL(f)}};return <section className="tool-page section"><div className="tool-head"><span className="eyebrow">01 / PALMISTRY</span><h1>Read the story<br/><em>in your hands.</em></h1><p>Share a clear photograph of your palm. Our AI will trace the traditional language of its lines with care.</p></div><div className="palm-layout"><div className="upload-zone">{image?<img className="preview" src={image} alt="Palm preview" data-testid="palm-image-preview"/>:<><div className="upload-icon"><Upload/></div><h3>Drop your palm photo here</h3><p>JPG, PNG or WEBP · up to 10MB</p></>}<label className="gold-btn upload-label" data-testid="palm-upload-label">{image?"Choose a different photo":"Upload a photo"}<input data-testid="palm-upload-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/></label></div><div className="tool-side"><h3>Which hand is this?</h3><div className="segmented">{["left","right","both"].map(x=><button key={x} data-testid={`hand-${x}-button`} className={hand===x?"selected":""} onClick={()=>setHand(x)}>{x}</button>)}</div><div className="instruction-list">{["Use soft, even lighting","Keep the entire palm visible","Separate fingers naturally","Hold the camera directly above"].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div><button className="gold-btn full" disabled={!image||loading} data-testid="analyze-palm-button" onClick={()=>onSubmit({image_base64:image,hand})}>{loading?<><span className="spinner"/>Analyzing your palm...</>:<>Begin my reading <ArrowRight size={16}/></>}</button><p className="micro-note">Your photo is used only to create this reading.</p></div></div></section>}
function PalmResult({data,go}){return <section className="section result-page"><div className="result-head"><span className="eyebrow">YOUR PALM READING · {data?.hand?.toUpperCase()} HAND</span><h1>Patterns, not<br/><em>predictions.</em></h1><p>Traditional palmistry interpreted with responsible AI guidance.</p></div><div className="reading-content"><div className="reading-card"><div className="reading-label"><Sparkles size={16}/> AI INTERPRETATION</div><div className="reading-text" data-testid="palm-reading-result">{data?.reading}</div></div><aside><div className="aside-note"><ShieldCheck/><strong>Keep this reflective</strong><p>Lines on your palm can change over time. Use this reading as a prompt for self-reflection, not a fixed outcome.</p></div><button className="ghost-btn full" data-testid="new-palm-button" onClick={()=>go("Palm Reading")}>Read another palm</button></aside></div></section>}
function KundliForm({onSubmit,loading,notify,isBundle,go}){const [f,setF]=useState({name:"",dob:"",birth_time:"",birthplace:"",latitude:null,longitude:null,timezone_name:null});const [suggestions,setSuggestions]=useState([]);const [searching,setSearching]=useState(false);const [showList,setShowList]=useState(false);const update=k=>e=>setF({...f,[k]:e.target.value,...(k==="birthplace"?{latitude:null,longitude:null,timezone_name:null}:{})});
  useEffect(()=>{const q=f.birthplace?.trim()||"";if(q.length<3||(f.latitude&&f.longitude)){setSuggestions([]);return}const t=setTimeout(async()=>{setSearching(true);try{const r=await api.get(`/geocode/search`,{params:{q}});setSuggestions(r.data?.results||[]);setShowList(true)}catch{setSuggestions([])}finally{setSearching(false)}},350);return()=>clearTimeout(t)},[f.birthplace,f.latitude,f.longitude]);
  const pick=(s)=>{setF(x=>({...x,birthplace:s.display_name,latitude:s.latitude,longitude:s.longitude,timezone_name:s.timezone}));setSuggestions([]);setShowList(false)};
  const submit=e=>{e.preventDefault();if(!f.latitude||!f.longitude||!f.timezone_name){notify?.("Please pick a birthplace from the suggestions so we can resolve exact coordinates.");return}onSubmit({name:f.name,dob:f.dob,birth_time:f.birth_time,birthplace:f.birthplace,latitude:f.latitude,longitude:f.longitude,timezone_name:f.timezone_name})};
  return <section className="section form-page"><div className="form-intro"><span className="eyebrow">02 / VEDIC ASTROLOGY {isBundle?"· BUNDLE STEP 1/2":""}</span><h1>Create your<br/><em>Kundli.</em></h1><p>Your birth details become a map — a traditional Jyotish profile for reflection, context, and curiosity.</p></div><form className="kundli-form" data-testid="kundli-form" onSubmit={submit}><div className="form-grid"><label>Full name<input data-testid="kundli-name-input" required value={f.name} onChange={update("name")} placeholder="e.g. Anika Sharma"/></label><label className="location-field">Birthplace<input data-testid="kundli-birthplace-input" required value={f.birthplace} onChange={update("birthplace")} onFocus={()=>setShowList(true)} placeholder="Start typing a city, then pick a match" autoComplete="off"/>{showList&&(suggestions.length>0||searching)&&<div className="location-suggestions" data-testid="location-suggestions">{searching&&<div className="location-suggestion muted">Searching…</div>}{suggestions.map(s=><button type="button" key={`${s.latitude}-${s.longitude}`} className="location-suggestion" data-testid="location-suggestion" onClick={()=>pick(s)}><MapPin size={14}/><span><b>{s.display_name}</b><small>{s.latitude.toFixed(3)}, {s.longitude.toFixed(3)} · {s.timezone}</small></span></button>)}</div>}{f.latitude&&f.longitude&&<small className="location-resolved" data-testid="location-resolved">Selected: {f.latitude.toFixed(3)}, {f.longitude.toFixed(3)} · {f.timezone_name}</small>}</label><label>Date of birth<input data-testid="kundli-dob-input" required type="date" value={f.dob} onChange={update("dob")}/></label><label>Exact birth time<input data-testid="kundli-time-input" required type="time" value={f.birth_time} onChange={update("birth_time")}/></label></div><div className="form-foot"><div className="form-privacy"><ShieldCheck size={17}/><span>Details are stored privately<br/><small>Coordinates and timezone are resolved for the calculation.</small></span></div><button className="gold-btn" disabled={loading} data-testid="generate-kundli-button">{loading?<><span className="spinner"/>Calculating...</>:<>Generate my Kundli <ArrowRight size={16}/></>}</button></div><p className="micro-note">Planetary positions are calculated server-side with Swiss Ephemeris using the Lahiri sidereal system. AI only interprets returned calculations.</p></form></section>}
function KundliResult({data,go,isBundle}){return <section className="section result-page"><div className="result-head split"><div><span className="eyebrow">YOUR VEDIC PROFILE {isBundle?"· BUNDLE STEP 1/2":""}</span><h1>{data?.name||"Your"}<br/><em>Kundli.</em></h1><p>{data?.birthplace} · {data?.dob} · {data?.birth_time}</p></div><span className="status-badge" data-testid="kundli-engine-status">{data?.engine_status}</span></div><div className="chart-summary"><div className="chart-visual" style={{backgroundImage:`url(${img.chart})`}}><div className="chart-ring"><span>ॐ</span><small>{data?.lagna}</small></div></div><div className="vitals"><Vital label="Lagna / Ascendant" value={data?.lagna}/><Vital label="Rashi / Moon sign" value={data?.rashi}/><Vital label="Nakshatra" value={data?.nakshatra?.name ? `${data.nakshatra.name} · Pada ${data.nakshatra.pada}` : "—"}/><Vital label="Timezone" value={data?.coordinates?.timezone}/></div></div><div className="planet-table"><div className="reading-label"><Stars size={16}/> PLANETARY POSITIONS</div>{data?.planets?.map(p=><div className="planet-row" key={p.planet}><b>{p.planet}</b><span>{p.sign}</span><small>{p.house} house</small></div>)}</div><div className="interpretation"><div><span className="eyebrow">AI ASTROLOGY INTERPRETATION</span><h2>Read between<br/><em>the lines.</em></h2></div><div className="interpretation-copy" data-testid="kundli-interpretation">{data?.interpretation}</div></div>{isBundle?<button className="gold-btn" data-testid="bundle-next-palm-button" onClick={()=>go("Palm Reading")}>Next: read my palm <ArrowRight size={16}/></button>:<button className="gold-btn" data-testid="ask-kundli-from-result-button" onClick={()=>go("Dashboard")}>Ask your Kundli <MessageCircle size={16}/></button>}</section>}
function Vital({label,value}){return <div className="vital"><span>{label}</span><strong>{value||"—"}</strong></div>}
function Dashboard({user,kundli,go}){const [question,setQuestion]=useState(""),[answer,setAnswer]=useState("");const ask=async e=>{e.preventDefault();if(!question)return;try{const r=await api.post("/chat",{question});setAnswer(r.data.answer)}catch(e){setAnswer(e.response?.data?.detail||"Create a Kundli first to ask questions.")}};return <section className="section dashboard"><div className="dash-head"><div><span className="eyebrow">YOUR PRIVATE COSMOS</span><h1>Good to see you,<br/><em>{user?.email?.split("@")[0]||"traveller"}.</em></h1></div><div className="dash-orbit"><Moon size={28}/><span>YOUR<br/>DASHBOARD</span></div></div><div className="dash-grid"><div className="dash-card main-card"><div className="card-top"><span className="eyebrow">MY KUNDLI</span><Stars size={18}/></div>{kundli?<><h2>{kundli.name}</h2><p>{kundli.lagna} ascendant · {kundli.rashi} moon</p><button className="text-link" data-testid="dashboard-view-kundli-button" onClick={()=>go("Kundli result")}>View full chart <ArrowRight size={16}/></button></>:<><h2>Your map awaits.</h2><p>Enter your birth details to create a personal Vedic profile.</p><button className="gold-btn" data-testid="dashboard-create-kundli-button" onClick={()=>go("Kundli")}>Create my Kundli <ArrowRight size={16}/></button></>}</div><div className="dash-card palm-card"><span className="eyebrow">PALM READINGS</span><h2>Read the lines<br/><em>again.</em></h2><button className="ghost-btn" data-testid="dashboard-palm-button" onClick={()=>go("Palm Reading")}>New reading <Upload size={15}/></button></div><div className="dash-card chat-card"><div className="card-top"><span className="eyebrow">ASK YOUR KUNDLI</span><MessageCircle size={18}/></div><h2>One question<br/>at a time.</h2><form onSubmit={ask} data-testid="chat-form"><input data-testid="chat-question-input" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What does my 10th house indicate?"/><button className="gold-btn" data-testid="chat-submit-button">Ask <ArrowRight size={15}/></button></form>{answer&&<div className="chat-answer" data-testid="chat-answer">{answer}</div>}</div></div></section>}
function Compatibility(){return <section className="section coming"><span className="eyebrow">03 / RELATIONSHIPS</span><h1>Two stories,<br/><em>one shared sky.</em></h1><p>Kundli Matching is coming soon. We’re shaping a thoughtful Guna Milan experience for curious hearts — never a verdict on love.</p><div className="coming-mark"><Stars size={42}/></div></section>}
const PACKAGES = {
  palm: {id:"palm", title:"AI Palm Reading", price:99, cta:"Read My Palm — ₹99", items:["AI palm image analysis","Major palm line interpretation","Personality insights","Career insights","Relationship insights","Finance insights","General future outlook"]},
  kundli: {id:"kundli", title:"AI Kundli", price:99, cta:"Create My Kundli — ₹99", items:["Vedic Kundli","Lagna / Ascendant","Rashi","Nakshatra","Planetary positions","Houses","Dasha information where available","AI-powered personalized interpretation","Ask Your Kundli AI"]},
  bundle: {id:"bundle", title:"Palm + Kundli", price:159, cta:"Get Both — ₹159", featured:true, saves:39, separately:198, items:["Everything in AI Palm Reading","Everything in AI Kundli","Both detailed reports linked in one dashboard"]}
};
function PricingCards({startPackage}){return <div className="pricing-grid" data-testid="pricing-grid">{["palm","kundli","bundle"].map(id=><PackageCard key={id} pkg={PACKAGES[id]} onStart={()=>startPackage(id)}/>)}</div>}
function PackageCard({pkg,onStart}){return <div className={pkg.featured?"price-card featured":"price-card"} data-testid={`pricing-card-${pkg.id}`}>{pkg.featured&&<span className="popular" data-testid="pricing-save-badge">SAVE ₹{pkg.saves}</span>}<span className="eyebrow">{pkg.title}</span><strong data-testid={`pricing-amount-${pkg.id}`}>₹{pkg.price}<small>one-time</small></strong>{pkg.featured&&<small className="strike-line">Separately ₹{pkg.separately} · <b>Save ₹{pkg.saves}</b></small>}{pkg.items.map(i=><div key={i}><Check size={15}/>{i}</div>)}<button className={pkg.featured?"gold-btn full":"ghost-btn full"} data-testid={`pricing-cta-${pkg.id}`} onClick={onStart}>{pkg.cta}</button></div>}
function Pricing({startPackage}){return <section className="section pricing"><span className="eyebrow">A LITTLE MORE DEPTH</span><h1>Choose your<br/><em>constellation.</em></h1><PricingCards startPackage={startPackage}/><p className="micro-note">Palm Reading + Kundli separately: ₹198 · Bundle: ₹159 · You save ₹39. Payment gateway integration required to activate purchases.</p></section>}
function Checkout({pkg,onProceed,go,notify}){const [confirming,setConfirming]=useState(false);const p=PACKAGES[pkg]||PACKAGES.palm;const attempt=()=>{setConfirming(true);setTimeout(()=>{setConfirming(false);notify?.("Payment gateway not yet connected. Continue with the free preview to explore your reading.","error")},1200)};
  return <section className="section checkout" data-testid="checkout-view"><div className="checkout-head"><span className="eyebrow">CHECKOUT · {p.title.toUpperCase()}</span><h1>Confirm your<br/><em>reading.</em></h1><p>You're about to unlock <b>{p.title}</b> for <b data-testid="checkout-amount">₹{p.price}</b>. {p.featured&&<span>Bundle saves you ₹{p.saves} vs ₹{p.separately} separately.</span>}</p></div><div className="checkout-grid"><div className="checkout-summary"><div className="reading-label"><Sparkles size={16}/> ORDER SUMMARY</div><div className="checkout-line"><span>{p.title}</span><b>₹{p.price}</b></div>{p.featured&&<div className="checkout-line muted-line"><span>You save vs separate purchases</span><b>-₹{p.saves}</b></div>}<div className="checkout-line total"><span>Total</span><b>₹{p.price}</b></div><ul className="checkout-items">{p.items.map(i=><li key={i}><Check size={13}/>{i}</li>)}</ul></div><div className="checkout-pay"><div className="pay-note"><Lock size={16}/><div><strong>Payment gateway not yet connected</strong><p>This MVP shows the full pricing structure but does not process live payments. A Razorpay (recommended for INR) or Stripe integration is required to charge ₹{p.price}. Preview access is enabled below.</p></div></div><button className="gold-btn full" data-testid="checkout-pay-button" onClick={attempt} disabled={confirming}>{confirming?<><span className="spinner"/>Contacting gateway…</>:<>Complete payment · ₹{p.price} <Lock size={15}/></>}</button><button className="ghost-btn full preview-btn" data-testid="checkout-preview-button" onClick={onProceed}>Continue with free preview <ArrowRight size={15}/></button><button className="text-btn" data-testid="checkout-back-button" onClick={()=>go("Overview")}>← Back to pricing</button></div></div></section>}
export default App;